version: '3.3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dogs_db
      POSTGRES_PASSWORD: dogpassword
    restart: always

  app:
    depends_on:
      - db
    image: dogs-app:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dogs_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: dogpassword
    ports:
      - "8080:8080"
    restart: always
